# 策略設定藍圖 | Strategy Configuration Blueprint
metadata:
  name: "adx_trend"
  symbol: "ETHUSDT"
  notes: "ADX趨勢動能策略 | ADX Trend Momentum Strategy"
market:
  interval: "1h"
  base_currency: "ETH"
  quote_currency: "USDT"
risk:
  risk_per_trade: 1.0
  max_daily_loss: 5.0
  slippage: 0.1
data:
  data_source: "binance"
  output_dir: "data/results"
parameters:
  ema_period: 200
  adx_threshold: 50
  stoch_period: 14
  risk_reward: 1.0
